### PR TITLE
Allow for overrides with a date prior than the original instance

### PR DESCRIPTION
**Pull request by mattjameswade**
Allow for overrides with a date prior than the original instance

### CODE REVIEW

**Comment by benplummer** [comment]
Thanks for submitting this. Do you have an example of two events which cause the issue that I can have a look at please?

**Comment by mattjameswade** [comment]
Dump of a sqlite db with events and recurrent_events . Please ignore change_id column, it is specific to my implementation.



0|id|integer|1||1
1|change_id|integer|1||0
2|start_date|datetime|1||0
3|end_date|datetime|1||0
4|parent_id|integer|0||0
5|occurrence_date|datetime|0||0
6|created_at|datetime|1||0
7|updated_at|datetime|1||0
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE "events" ("id" integer not null primary key autoincrement, "change_id" integer not null, "start_date" datetime not null, "end_date" datetime not null, "parent_id" integer null, "occurrence_date" datetime null, "created_at" datetime not null, "updated_at" datetime not null, foreign key("change_id") references "changes"("id"));
INSERT INTO "events" VALUES(2,2,'2016-02-15 22:00:00','2016-02-16 03:00:00',1,'2016-02-16 22:00:00','2016-01-16 22:00:00','2016-01-16 22:00:00');
COMMIT;



0|id|integer|1||1
1|change_id|integer|1||0
2|start_date|datetime|1||0
3|end_date|datetime|1||0
4|parent_id|integer|0||0
5|occurrence_date|datetime|0||0
6|recurrence_type|varchar|0||0
7|recurrence_until|datetime|0||0
8|created_at|datetime|1||0
9|updated_at|datetime|1||0
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE "recurrent_events" ("id" integer not null primary key autoincrement, "change_id" integer not null, "start_date" datetime not null, "end_date" datetime not null, "parent_id" integer null, "occurrence_date" datetime null, "recurrence_type" varchar null, "recurrence_until" datetime null, "created_at" datetime not null, "updated_at" datetime not null, foreign key("change_id") references "changes"("id"));
INSERT INTO "recurrent_events" VALUES(1,2,'2016-01-16 22:00:00','2016-01-17 03:00:00',NULL,NULL,'monthly','2019-01-17 03:00:00','2016-01-16 20:24:21','2016-01-16 20:24:21');
COMMIT;

**Comment by benplummer** [comment]
I'm not sure if this issue arises in the sorting of the events beforehand. 

Apologies for any inconvenience but would you be able to add do a `var_dump($this->allEvents);die;` on [line 189](https://github.com/mattjameswade/calendarful/blob/mattjameswade-patch-1/src/Calendar/Calendar.php#L189) and post the result please?

**Comment by mattjameswade** [comment]
I've attached the dump.

I didn't touch the sorting that happens on line 188, specifically because it would then break the sorting overall. 

Essentially, my patch just says "If this event is an override, use it and put it in $events, otherwise if this event already has a entry in $events then we have an override in there, so don't put this normal occurrence."

This should work for cases where the override is before the normal occurrence or after the normal occurrence.

The way the code currently stands, it will always use the last occurrence, whether there is an override or not.

**Comment by benplummer** [comment]
Yes I thought this was the case. Thanks for highlighting the issue and providing a solution!

I'm going to be overhauling the package for the next major version. I'll take these sort of issues into account and try to handle them more elegantly than the current versions do so.

**Pull request merged**
